# Generated by Django 3.2 on 2021-04-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='datetime',
            field=models.DateTimeField(auto_created=True, default='2021-07-12 15:00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alert')),
            ],
        ),
    ]
