# Generated by Django 3.2 on 2021-04-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210423_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
