# Generated by Django 3.2 on 2021-04-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210425_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('ip', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
