# Generated by Django 3.2 on 2021-04-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
