# Generated by Django 3.2 on 2021-04-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_visit_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='email',
        ),
    ]
